name: 'Copilot Setup Steps'

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Japanese fonts for Playwright screenshots
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            fonts-noto-cjk \
            fonts-ipafont \
            fonts-ipaexfont \
            locales  # Required for locale-gen command

          # Configure UTF-8 Japanese locale
          sudo locale-gen ja_JP.UTF-8
          echo "LANG=ja_JP.UTF-8" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Prepare Nuxt
        run: pnpm postinstall

      - name: Verify Japanese fonts installation
        run: |
          echo "📝 Checking installed Japanese fonts..."
          total_fonts=$(fc-list :lang=ja | wc -l)
          echo "Total Japanese fonts installed: $total_fonts"
          if fc-list :lang=ja | grep -q "Noto Sans CJK"; then
            echo "✅ 'Noto Sans CJK' font is installed."
          else
            echo "❌ 'Noto Sans CJK' font is missing."
            exit 1
          fi
          if fc-list :lang=ja | grep -q "IPAexMincho"; then
            echo "✅ 'IPAexMincho' font is installed."
          else
            echo "❌ 'IPAexMincho' font is missing."
            exit 1
          fi
