name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Japanese fonts for Playwright screenshots
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            fonts-noto-cjk \
            fonts-ipafont \
            fonts-ipaexfont \
            locales
          
          # Configure UTF-8 Japanese locale
          sudo locale-gen ja_JP.UTF-8
          echo "LANG=ja_JP.UTF-8" | sudo tee -a /etc/environment
          echo "LC_ALL=ja_JP.UTF-8" | sudo tee -a /etc/environment

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Prepare Nuxt
        run: pnpm postinstall

      - name: Verify Japanese fonts installation
        run: |
          echo "📝 Checking installed Japanese fonts..."
          fc-list :lang=ja | head -10
          echo "✅ Japanese fonts verification completed"