name: Reply to review

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [review_requested]

jobs:
  review:
    runs-on: ubuntu-latest
    if: >-
      (github.event_name == 'issue_comment' && 
       github.event.issue.pull_request != null && 
       github.event.sender.id == 8929706 && 
       contains(github.event.comment.body, '@akubiusa') && 
       contains(github.event.comment.body, 'review')) ||
      (github.event_name == 'pull_request' && 
       github.event.action == 'review_requested' && 
       github.event.requested_reviewer.id == 222856114)

    steps:
      - name: Set variables
        run: |
          if [ "${{ github.event_name }}" = "issue_comment" ]; then
            echo "PR_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
            echo "MESSAGE=It was reviewed by a request by comment." >> $GITHUB_ENV
          else
            echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
            echo "MESSAGE=It was reviewed by a reviewer assignment." >> $GITHUB_ENV
          fi
      - name: Review
        run: |
          gh pr review ${{ env.PR_NUMBER }} -R "$GITHUB_REPOSITORY" -a -b "${{ env.MESSAGE }}"
        env:
          GITHUB_TOKEN: ${{ secrets.AKUBIUSA_ACCESS_TOKEN }}
